#
# Travis Project Descriptor
#
# See http://about.travis-ci.org/docs/user/build-configuration/
#

# build matrix
language: python
python:
    - "2.7"
    - "2.6"

# command to install dependencies
# ("dpkg-dev" omitted due to errors on Travis)
install:
    - "sudo apt-get install dput dh-make"
    - "test $TRAVIS_PYTHON_VERSION = 2.5 || pip install -M 'pylint>=1.0'"

# command to run tests
script: "bash -x dput-webdav/test.sh"
